# Generated by Django 5.2 on 2026-09-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='is_enabled',
            new_name='is_enable',
        ),
    ]
